### ISSUE TITLE
The openai key is not effective.

### ISSUE THREAD

**Issue by JustDo** [pAIrprogio/vscode-ui-sketcher#1]
My OpenAI GPT is version 4.0. When I use "UI Sketcher: Set OpenAI API Token" to set the key and click on Make Real, it shows an error message "UI Sketcher: Unable to create completion due to issues with Open AI API". Then I borrowed someone else's key from their OpenAI account in UI Sketcher: Set OpenAI API Token, and when I clicked on Make Real again, it was able to generate code normally. Their OpenAI ChatGPT account is version 3.5. Why is that?

Note: The key for my GPT 4.0 can be used normally in other applications.

![image](https://github.com/pAIrprogio/vscode-ui-sketcher/assets/4507113/59787ee2-788a-43f6-8cb1-65fe117424aa)

**Comment by rexsaurus** [comment]
i get same error, I guess Im GPT 4.0. Unable to resolve.

**Comment by sagark1510** [comment]
same for me. I'm GPT 4.0

**Comment by MikeCheng1208** [comment]
I'm GPT 4.0, always not effective.

**Comment by Henryhaohao** [comment]
@JustDo @rexsaurus @sagark1510 @MikeCheng1208 

Have you all set **`max_token`** value? 
Because the offical `gpt-4-vision-preview` api returns a maximum of 4,096 output tokens.
So just remove its setting, or set the value to less than or equal to `4096`.
This is how I solved this problem myself.
Hope it helps you~

**Comment by yleflour** [comment]
@Henryhaohao thanks, I'll update the value's description to include this information

For the others, do you all have access to GPT4V?

**Comment by yleflour** [comment]
1.1.6 now includes validation for the maxTokens settings, thank you for reporting
