### ISSUE TITLE
Would be super nice if copy/paste screenshot is supported

### ISSUE THREAD

**Issue by jiangyan** [pAIrprogio/vscode-ui-sketcher#2]
![image](https://github.com/pAIrprogio/vscode-ui-sketcher/assets/854144/feaacce0-3125-43bf-bea4-b0041892cbee)
real world case, is when we implement frontend work, we can just capture a screen shot from product's axure design, it would be much better if copy/paste screenshot is supported

**Comment by telemakhos** [comment]
just click the upload image button? 

![image](https://github.com/pAIrprogio/vscode-ui-sketcher/assets/2261077/acb46165-66d0-41bd-a739-1ec913d5b2c6)

**Comment by jiangyan** [comment]
thanks, well, I know there's the upload button, that's why I said 'copy & paste', the screenshot copy and paste into sketcher can be easily done through keyboard, it's like a second, done. However, through 'upload', you have to save screenshot somewhere and click upload button to browse the folder you saved, it's just not that fast. It's not an issue, it's just a feature suggestion.

**Comment by yleflour** [comment]
I updated the extension with copy/paste support a couple weeks ago. Are you still having issues?

**Comment by jiangyan** [comment]
> I updated the extension with copy/paste support a couple weeks ago. Are you still having issues?

Man! You are my savior, awesome work!😊
